### PR TITLE
Fix building with SCons on Mac OSx

### LINKED ISSUE #55: SCons samples don't run on on OSX.
I seem unable to build on OSX Catalina 10.15.4

~~Autotools fails at the end of building:~~ Autotools working now, please update libtcod.

```
libtool:   error: CURRENT '-lpthread' must be a nonnegative integer
libtool:   error: '-lpthread' is not valid version information
make: *** [libtcod.la] Error 1
```

scons also fails, Xcode seems to have deprecated/broken i386:

```
ld: symbol(s) not found for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)
scons: *** [libtcod-1.15.1-x86.x86_64-DEBUG-macos/libtcod.dylib] Error 1
scons: building terminated because of errors.
```

I noticed your travis builds are working for OSX, but it appears you are using Xcode 9. Does this work at all with updated Xcode versions? I'm just using the Xcode command line tools, installed via `xcode-select --install`. It would be very inconvenient to say the least to require an old Xcode installation.

### PR DESCRIPTION
**Pull request by MichaelMackus**
This successfully builds & runs the samples now on Mac OSx using SCons.

Fixes #55

### CODE REVIEW

**Comment by HexDecimal** [comment]
This also reveals some of the poor choices I made with the SCons builder.  I wish I had built the binary files into a `bin/` directory when I made the original script.

**Comment by MichaelMackus** [comment]
I can definitely modify it to unpack the sources into the `Frameworks` directory instead of the `dependencies` directory, but I was just following what it looked like was being done for the win32 code. In the Windows-specific code, everything is linking DLLs within the SDL2_PATH directory, hence my rpath addition.

**Comment by HexDecimal** [comment]
Did you run the samples with this setup?  You might need to add the rpath: `@loader_path/Frameworks`.

**Comment by MichaelMackus** [comment]
Yes, it works. The Frameworks folder is already being loaded at runtime; I
even tried symlinking SDL2 in there manually and it worked.
