### ISSUE TITLE
SCons samples don't run on on OSX.

### ISSUE THREAD

**Issue by MichaelMackus** [libtcod/libtcod#55]
I seem unable to build on OSX Catalina 10.15.4

~~Autotools fails at the end of building:~~ Autotools working now, please update libtcod.

```
libtool:   error: CURRENT '-lpthread' must be a nonnegative integer
libtool:   error: '-lpthread' is not valid version information
make: *** [libtcod.la] Error 1
```

scons also fails, Xcode seems to have deprecated/broken i386:

```
ld: symbol(s) not found for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)
scons: *** [libtcod-1.15.1-x86.x86_64-DEBUG-macos/libtcod.dylib] Error 1
scons: building terminated because of errors.
```

I noticed your travis builds are working for OSX, but it appears you are using Xcode 9. Does this work at all with updated Xcode versions? I'm just using the Xcode command line tools, installed via `xcode-select --install`. It would be very inconvenient to say the least to require an old Xcode installation.

**Comment by HexDecimal** [comment]
I pushed updates to the develop branch.  You can now change the architecture of MacOS builds in SCons and it no longer defaults to making a universal build.

**Comment by MichaelMackus** [comment]
That seemed to get further, thank you. It is building the "libtcod.dylib" file now. The samples still aren't building properly, and I'm still unable to run my application or the samples - it is getting an error referencing SDL2:

```./samples_c
dyld: Library not loaded: @rpath/SDL2.framework/Versions/A/SDL2```

There was also an error from scons build when trying `scons develop_all`:

```gcc -o libtcod-1.16.0-alpha.10-x86_64-DEBUG-macos/.deps -arch x86_64 -framework ApplicationServices -framework SDL2 -F./dependencies/SDL2.framework/.. -rpath @loader_path/ -rpath @loader_path/../Frameworks -rpath /Library/Frameworks -rpath /System/Library/Frameworks -Llibtcod-1.16.0-alpha.10-x86_64-DEBUG-macos -L/Users/michael/dev/deeprl/libtcod -ltcod
Undefined symbols for architecture x86_64:
  "_main", referenced from:
     implicit entry/start for main executable
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
scons: *** [libtcod-1.16.0-alpha.10-x86_64-DEBUG-macos/.deps] Error 1
scons: building terminated because of errors.```

As a side note, is it assumed with scons I will be using scons to build my project? I noticed pkg-config does not seem to work (out of the box) with the scons build, which I would much prefer. But I'm OK with packaging two build systems in my application if that is the preferred way.

Thanks for your help and the rapid turnaround!

**Comment by HexDecimal** [comment]
> I'm still unable to run my application or the samples - it is getting an error referencing SDL2:
>
> dyld: Library not loaded: @rpath/SDL2.framework/Versions/A/SDL2

Other than the unit tests I've never had a chance to actually run the samples on MacOS lately.  It's possible that I've never installed the SDL2.framework where the executables needed them to be.

I think putting the SDL2.framework next to the executable or installing it to your system will fix that link error.  I'd like you to verify that if possible.

SDL2.framework can be put in other places too if you know how to modify rpath's.

> As a side note, is it assumed with scons I will be using scons to build my project?

SCons just builds the library.  I'm not sure how to setup pkg-config for it and the SCons script is so messy that I'm not sure it's even desirable.

There's Conan if you want the libtcod's build system to be part of your program.  It's what's used to build and run the unit tests and it will handle the SDL2 issues you're having.  The readme in the samples directory has instructions on how to use Conan.

**Comment by MichaelMackus** [comment]
Thanks, I'll try messing with the SDL2 path after work.

FYI I do have SDL2 already installed system-wide.

**Comment by HexDecimal** [comment]
As a framework? Or is it some other variation of SDL2?  I don't think I could explain why a system installed framework wouldn't be found.

**Comment by MichaelMackus** [comment]
Yes, I installed SDL2 via homebrew: `brew install sdl2`. The includes &
lib files are both installed globally.

**Comment by HexDecimal** [comment]
Frameworks are their own weird thing. I don't think it's the same as what you'd get from brew.  Because SCons links with a Framework it doesn't expect an `libSDL2.so` file it instead expects the whole `SDL2.framework/Versions/A/SDL2` directory structure.  I'd need to reconfigure SCons if I wanted it to link to the brew files.

SDL2.framework can be found as a `.dmg` download on the official site:
https://www.libsdl.org/download-2.0.php

**Comment by MichaelMackus** [comment]
I finally got this building on autotools. I have pushed a pull request that addresses this. I'm not sure why scons isn't working, since it *is* pulling in the SDL2 framework into the dependencies folder.

**Comment by HexDecimal** [comment]
The dependencies folder is not the correct folder for it to link at runtime.  It'd need to be at one of the rpath locations listed here:

https://github.com/libtcod/libtcod/blob/ffdfada53ac04ad6c2cef21ae11e875b876edcb6/buildsys/scons/SConstruct#L365-L368
Where `@loader_path` is the executable file.

**Comment by HexDecimal** [comment]
I agree that SCons should handle this itself, but the script is hard to work with since it was my first ever use of SCons.

As long as you're happy with Autotools then I'll consider this a lower priority.

**Comment by MichaelMackus** [comment]
I've created a new PR that fixes the SCons build on Mac OSx by adding the dependencies directory to the rpath. This builds the samples, and they seem to run fine now, but it is still failing with an error (after the compilation of apfviewer):

```
gcc -o libtcod-1.16.0-alpha.10-x86_64-DEBUG-macos/.deps -arch x86_64 -framework ApplicationServices -framework SDL2 -F./dependencies/SDL2.framework/.. -rpath @loader_path/ -rpath @loader_path/.././dependencies -rpath @loader_path/../Frameworks -rpath /Library/Frameworks -rpath /System/Library/Frameworks -Llibtcod-1.16.0-alpha.10-x86_64-DEBUG-macos -L/Users/michael/dev/deeprl/libtcod -ltcod
Undefined symbols for architecture x86_64:
  "_main", referenced from:
     implicit entry/start for main executable
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
scons: *** [libtcod-1.16.0-alpha.10-x86_64-DEBUG-macos/.deps] Error 1
scons: building terminated because of errors.
```
