### PR TITLE
Update ax_pthread.m4 autotools macro

### LINKED ISSUE #55: SCons samples don't run on on OSX.
I seem unable to build on OSX Catalina 10.15.4

~~Autotools fails at the end of building:~~ Autotools working now, please update libtcod.

```
libtool:   error: CURRENT '-lpthread' must be a nonnegative integer
libtool:   error: '-lpthread' is not valid version information
make: *** [libtcod.la] Error 1
```

scons also fails, Xcode seems to have deprecated/broken i386:

```
ld: symbol(s) not found for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)
scons: *** [libtcod-1.15.1-x86.x86_64-DEBUG-macos/libtcod.dylib] Error 1
scons: building terminated because of errors.
```

I noticed your travis builds are working for OSX, but it appears you are using Xcode 9. Does this work at all with updated Xcode versions? I'm just using the Xcode command line tools, installed via `xcode-select --install`. It would be very inconvenient to say the least to require an old Xcode installation.

### PR DESCRIPTION
**Pull request by MichaelMackus**
This fixes building via autotools on Mac OSx Catalina.

See #55 (at least for autotools)

### CODE REVIEW

**Comment by HexDecimal** [comment]
I'm glad you looked into it and confirmed this was the problem.

If you don't consider this PR as enough to close your issue then you could avoid putting `fix` before the number `#55`, which will let you reference the issue in the PR without closing it when merged.

I'll merge this not too long after the tests pass.

**Comment by MichaelMackus** [comment]
No problem, I updated the comment.
